dist: bionic
language: java
jdk:
  - openjdk13

before_install:
  - openssl aes-256-cbc -K $encrypted_0e40c5863533_key -iv $encrypted_0e40c5863533_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key

addons:
  sonarcloud:
    organization: boyshawn-github
    token:
      secure: D9gO4buKbRxZfMqBMumdh6XdqpkrdeVDsx86YXkXhgt9JqJOyHKT8fzhx2rfAXp+dFwfM7kwgcJkaaSrFuGljzWAJJrdwMF6wULfmRX6lyeA+F2lYRN9yBtzWGH8xOWv2IkwTjwEsagzlViz00faXMJcGckml66rENopeD/JyQ2ZrMxupXoj3KuaEJqwe6i0VVNpHztC+NKCwxS0OJOob66nb3LoSHlzVVHe6Ix6D6IgAK6TBd70AcZbJfmXVp3jgLzMoxJKkYpj18JfUF2cSE7I6zkw5T4kbKLT8ID/UsCQTCPbNM5baefrjAIezku4LYddgj62xX9yyaehm1wQPY38OEx2QhT+QZ6QHpdaTHAD2ZAvd1D2NMYGH3eUoZS3Ax3NFePNAaU/cz2qnktIEKHImqYa5U2jZwE/xds1+16A5bw+WKyIlZfXJVTmQftuHbZ5OZFUvv+D0ec7nSFpeJevGooA5/Y7hMvhEFF3IBGLJMJtqc0eHQINirOsaC84WFDcU0GW9mg43fYxBxIjo51TeyzWs5rszsiUI5LOhtbwkZ5MugCURGpAelbNazfyU6YGs15L1jTAvNQa42Z9kprsD2adQEjzcerq9EBpbLmuYm/aLYFs1JMP3bKqhqXrgkDqx4DkUemkUKIOkiYRPtk7LMH+kt2Gb3Vk4AgBjKM=

stages:
#  -test
  -release

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: mvn test
# Need not do this because this is already done as part of the SonarCloud addon
#    - stage: verify
#      name: "Generate Jacoco code coverage, and commit to SonarCloud"
#      script: sonar-scanner
    - stage: release
      name: "Only for master: Prepare devlieries for release"
      script:
        - git checkout $TRAVIS_BRANCH
        - mvn --batch-mode release:prepare -Dresume=false release:perform -DreleaseVersion=5.4 -Dmaven.javadoc.skip=true
        - mvn --batch-mode release:update-versions -DdevelopmentVersion=5.5
# Commit these stage off, they cannot be disable at the moment, so have to be commented. Will uncomment whenever there
# is need to deploy
#    - stage: install
#      name: "Install the package into the local repository"
#      script: mvn install
#    - stage: deploy
#      name: "Release to deployment, maven release"
#      script: mvn --batch-mode release:prepare -Dresume=false release:perform -DreleaseVersion=5.1
#    - stage: postDeploy
#      name: "Perform update development of maven release"
#      cript: mvn release:update-versions -DdevelopmentVersion=5.2
