name: 'Default post-commit hook check'
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      # Push events to branches matching refs/heads/master
      - master
  pull_request:
  create:
jobs:
  test:
    name: 'Unit test'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Test'
        run: mvn test --debug
  quality:
    name: 'Static code analysis'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Import GPG key'
        uses: crazy-max/ghaction-import-gpg@master
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: 'SonarCloud Scan'
        run: mvn clean verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    name: 'Deploy snapshot to nexus repository'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Import GPG key'
        uses: crazy-max/ghaction-import-gpg@master
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: 'Update password in settings.xml'
        run: sed --in-place 's/REPLACE_PASSWORD/${{ secrets.NEXUS_PASSWORD }}/' $GITHUB_WORKSPACE/settings.xml
#      - name: 'See setting.xml file'
#        run: cat /home/runner/.m2/settings.xml
      - name: 'Deploy'
        run: mvn deploy -DskipTests --settings $GITHUB_WORKSPACE/settings.xml
