name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: GitHub Actions for Apache Maven
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64