name: build
on: [push, pull_request]
jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Test'
        run: mvn test --debug
  quality:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Static code analysis'
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent package
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: D9gO4buKbRxZfMqBMumdh6XdqpkrdeVDsx86YXkXhgt9JqJOyHKT8fzhx2rfAXp+dFwfM7kwgcJkaaSrFuGljzWAJJrdwMF6wULfmRX6lyeA+F2lYRN9yBtzWGH8xOWv2IkwTjwEsagzlViz00faXMJcGckml66rENopeD/JyQ2ZrMxupXoj3KuaEJqwe6i0VVNpHztC+NKCwxS0OJOob66nb3LoSHlzVVHe6Ix6D6IgAK6TBd70AcZbJfmXVp3jgLzMoxJKkYpj18JfUF2cSE7I6zkw5T4kbKLT8ID/UsCQTCPbNM5baefrjAIezku4LYddgj62xX9yyaehm1wQPY38OEx2QhT+QZ6QHpdaTHAD2ZAvd1D2NMYGH3eUoZS3Ax3NFePNAaU/cz2qnktIEKHImqYa5U2jZwE/xds1+16A5bw+WKyIlZfXJVTmQftuHbZ5OZFUvv+D0ec7nSFpeJevGooA5/Y7hMvhEFF3IBGLJMJtqc0eHQINirOsaC84WFDcU0GW9mg43fYxBxIjo51TeyzWs5rszsiUI5LOhtbwkZ5MugCURGpAelbNazfyU6YGs15L1jTAvNQa42Z9kprsD2adQEjzcerq9EBpbLmuYm/aLYFs1JMP3bKqhqXrgkDqx4DkUemkUKIOkiYRPtk7LMH+kt2Gb3Vk4AgBjKM=
