name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Apache Maven Build Automation for Java Project
        uses: NishkarshRaj/Maven_Actions@0.1
        with:
          java-version: 14.0.1
