name: 'Master branch maven release'
on:
  push:
    branches:
      - master
jobs:
  quality:
    name: 'Static code analysis'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Import GPG key'
        uses: crazy-max/ghaction-import-gpg@master
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: 'SonarCloud Scan'
        run: mvn clean verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  release:
    name: 'Maven release'
    runs-on: 'ubuntu-20.04'
    # Skip commit made by maven-release
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: 'Set up JDK'
        uses: actions/setup-java@master
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: 'Import GPG key'
        uses: crazy-max/ghaction-import-gpg@master
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: 'Configure git commit'
        run: git config user.email "boyshawn@hotmail.com" && git config --global user.name "francis-pang"
      - name: 'Prepare release'
        run: mvn --batch-mode release:prepare -Dmaven.javadoc.skip=true -DskipTests
      - name: 'Update password in settings.xml'
        run: sed --in-place 's/REPLACE_PASSWORD/${{ secrets.NEXUS_PASSWORD }}/' $GITHUB_WORKSPACE/settings.xml
      - name: 'Actual release'
        run: mvn --batch-mode release:perform -Dmaven.javadoc.skip=true -DskipTests --settings $GITHUB_WORKSPACE/settings.xml

